################################################################################
# Stellar - Machine Learning on Graphs

version: '3'

networks:
  stellar-net:
    driver: bridge

services:
  ##############################################################################
  # Stellar Ingest - Data ingestion module.
  ingest:
    image: etd-docker01.it.csiro.au/stellar/ingest:0.0.2-SNAPSHOT
    # Example: no env var is currently used by the ingestor
    environment:
      - DEBUG=false
      - SOMEVER=123
    #entrypoint: flask initdb
    #depends_on:
    #  - db
    ports:
      - ${STELLAR_INGEST_REST_PORT}:3000
    volumes:
      - ${STELLAR_INGEST_DATAPATH}:/data/user
    networks:
      - stellar-net
  
  ##############################################################################
  # Stellar Search - Search module.

  # TODO: this  works but is  currently incomplete.  The original  Search docker
  # compose configuration needs the source  code, to get configuration files, to
  # run the remaining bits (Elastics search and Kibana).

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${STELLAR_SEARCH_ELASTIC_VERSION}
    volumes:
      - ${STELLAR_SEARCH_ELASTIC_CONFIG}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - ${STELLAR_SEARCH_ELASTIC_REST_PORT}:9200
      - ${STELLAR_SEARCH_ELASTIC_COMM_PORT}:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - stellar-net

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${STELLAR_SEARCH_ELASTIC_VERSION}
    volumes:
      - ${STELLAR_SEARCH_KIBANA_CONFIG}:/usr/share/kibana/config:ro
    ports:
      - ${STELLAR_SEARCH_KIBANA_PORT}:5601
    networks:
      - stellar-net
    depends_on:
      - elasticsearch

  db:
    image: postgres:9
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - ${STELLAR_SEARCH_DB_PORT}:5432
    networks:
      - stellar-net

  adminer:
    image: adminer
    restart: always
    ports:
        - ${STELLAR_SEARCH_ADMINER_PORT}:8080
    networks:
      - stellar-net

