################################################################################
# Stellar - Machine Learning on Graphs

version: '3.4'

networks:
  stellar-net:
    driver: bridge

services:
  ##############################################################################
  # Stellar Ingest - Data ingestion module.
  ingest:
    image: data61/stellar-ingest:0.0.2-SNAPSHOT
    # Example: no env var is currently used by the ingestor
    environment:
      - DEBUG=false
      - SOMEVER=123
    #entrypoint: flask initdb
    #depends_on:
    #  - db
    ports:
      - ${STELLAR_INGEST_REST_PORT}:3000
    volumes:
      - ${STELLAR_INGEST_DATAPATH}:/data/user
    networks:
      - stellar-net
  
  ##############################################################################
  # Stellar Search - Search module.

  search:
    # data61stellardev doesn't have permissions to push to data61/ org yet
    image: data61stellardev/stellar-search:0.0.1-SNAPSHOT
    command:
      - "--spring.profiles.active=docker"
      - "--spring.config.location=/etc/stellar-search/"
    volumes:
      - ${STELLAR_SEARCH_APP_CONFIG}/:/etc/stellar-search/:ro
      - ${STELLAR_SEARCH_DATAPATH}:/data/user
    ports:
      - ${STELLAR_SEARCH_REST_PORT}:8080
    depends_on:
      - elasticsearch
      - db
    networks:
      - stellar-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${STELLAR_SEARCH_ELASTIC_VERSION}
    volumes:
      - ${STELLAR_SEARCH_ELASTIC_CONFIG}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      # yellow (under replicated - which can happen for single node) and green status is considered healthy
      test:
        - "CMD-SHELL"
        - "curl -fs 'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s&filter_path=status' | grep -qE '(green|yellow)' || exit 1"
      interval: 1m
      timeout: 60s
      retries: 3
      start_period: 30s
    networks:
      - stellar-net

  db:
    image: postgres:alpine
    volumes:
      - ${STELLAR_DB_INITSCRIPTS}/:/docker-entrypoint-initdb.d/:ro
    restart: always
    environment:
      POSTGRES_PASSWORD: ${STELLAR_DB_PASSWORD} # only for the super user account
      # Don't define POSTGRES_USER, POSTGRES_DB, since multiple modules may want their own
      # DB and user. Instead define per-module roles in /docker-entrypoint-initdb.d/
      # See docker image doco https://hub.docker.com/_/postgres/
    healthcheck:
      test:
        - "CMD-SHELL"
        - 'pg_isready --username "$${POSTGRES_USER}" --dbname "$${POSTGRES_DB}" || exit 1'
      interval: 1m
      timeout: 60s
      retries: 3
      start_period: 30s
    networks:
      - stellar-net
