---
- name: add the nodejs repository for enteprise linux
  yum:
    name: https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm
    state: present

- name: install nodejs
  yum:
    name: nodejs
    state: latest
